export const textPresets = {
  headline: {
    label: 'Headline',
    text: 'BREAKING NEWS',
    fontSize: 66,
    fontWeight: 'bold',
    fontFamily: 'Impact',
    fill: '#ffffff',
    backgroundColor: '#d32f2f',
    padding: 20,
    textAlign: 'center',
    width: 740,
    charSpacing: 15,
  },
  subheadline: {
    label: 'Sub',
    text: 'TIN NONG',
    fontSize: 46,
    fontWeight: 'bold',
    fontFamily: 'Impact',
    fill: '#111111',
    backgroundColor: '#ffd400',
    padding: 14,
    textAlign: 'center',
    width: 600,
    charSpacing: 20,
  },
  caption: {
    label: 'Caption',
    text: 'Mo ta su kien dang dien ra tai hien truong...',
    fontSize: 30,
    fontWeight: 'normal',
    fontFamily: 'Arial',
    fill: '#ffffff',
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 16,
    textAlign: 'left',
    width: 700,
    lineHeight: 1.35,
  },
  plain: {
    label: 'Text',
    text: 'Your text',
    fontSize: 52,
    fontWeight: 'bold',
    fontFamily: 'Impact',
    fill: '#ffffff',
    backgroundColor: '',
    padding: 4,
    textAlign: 'center',
    width: 500,
    charSpacing: 10,
  },
}